routes/web.php
        // Route::get('/chart/releaseNotes', 'HomeController@releaseNotes')->name('charts.releaseNotes');
    });
    Route::group(['prefix'=>'inventory'], function(){
        Route::resource('/consumable','ConsumablesController');
        Route::get('/assign-equipment/suppandequitable', 'AssignEquipmentController@suppandequitable')->name('assign.suppandequitable');
        Route::get('/assign-equipment/autocomplete', 'AssignEquipmentController@autocomplete')->name('assign.autocomplete');
        Route::get('/assign-equipment/suppandequi', 'AssignEquipmentController@SuppliesandEquipments')->name('assign.suppandequi');
        Route::get('/assign-equipment/generaldata', 'AssignEquipmentController@generaldata')->name('assign.generaldata');
        Route::get('/assign-equipment/reloadtable', 'AssignEquipmentController@reloadtable')->name('assign.reloadtable');
        Route::get('/assign-equipment/getAssign/{year}', 'AssignEquipmentController@getAssign')->name('assign.getAssign');
        Route::put('/assign-equipment/functionRemoveAssign/{id}', 'AssignEquipmentController@functionRemoveAssign')->name('functionRemoveAssign');
        Route::get('/consumables/getConsumables/{year}', 'ConsumablesController@getConsumables')->name('consumables.getConsumables');
        Route::resource('/assign-equipment','AssignEquipmentController');
        Route::get('/remove-equipment/{id}', 'OfficeEquipmentController@removeEquipment')->name('removeEquipment');
        Route::put('/equipment/functionRemoveEquipment/{id}', 'OfficeEquipmentController@functionRemoveEquipment')->name('equipment.functionRemoveEquipment');
        Route::resource('/assign-equipment','AssignEquipmentController');
        Route::get('/office-equipment/getEquipments/{year}', 'OfficeEquipmentController@getEquipments')->name('equipment.getEquipments');
        Route::resource('/office-equipment', 'OfficeEquipmentController');
        Route::resource('/receiving', 'ReceivingController');
        Route::get('/consumables/image/{file}','ConsumablesController@getImage')->name('consumables.image');
        Route::get('/consumables/archived/{id}','ConsumablesController@archived')->name('consumable.archived');
        Route::get('/get-receiving/supplier', 'ReceivingController@supplierName')->name('get.supplier.name');
        Route::group(['prefix' => 'receivings'],function(){
            Route::get('/remove-receiving/{id}', 'ReceivingController@removeReceiving')->name('remove.receiving');
            Route::get('/get-receiving/{id}', 'ReceivingController@getPurchaseReceiving')->name('get.receiving');
            Route::get('/get-receivings/getReloadtable', 'ReceivingController@getReloadtable')->name('getReloadtable');
            Route::get('/get-receiving-list/{year}', 'ReceivingController@getReceivingList')->name('get.receiving.list');
            Route::put('/get-receiving/functionRemoveInventoryReceiving/{id}', 'ReceivingController@functionRemoveInventoryReceiving')->name('functionRemoveInventoryReceiving');

        });
        Route::get('/new-inventory/reloadtable/{id}', 'NewInventoryController@reloadtable')->name('new-inventory.reloadtable');
        Route::resource('/new-inventory', 'NewInventoryController');
    });
    Route::get('/disbursement-voucher/autocompleteClaimant', 'DisbursementVoucherController@autocompleteClaimant')->name('dv.autocompleteClaimant');
    Route::group(['prefix'=>'accounting'], function(){
        Route::resource('/roa-dv', 'DisbursementVoucherController');
        Route::get('/roa-dv/{id}/delete', 'DisbursementVoucherController@delete')->name('roa-dv.delete');
        Route::get('/roa-dv/{id}/print', 'DisbursementVoucherController@print')->name('roa-dv.print');
        Route::get('/roa-dvs/autocompleteOr', 'DisbursementVoucherController@autocompleteOr')->name('roa-dv.autocompleteOr');
        Route::get('/roa-dvs/ORPad', 'DisbursementVoucherController@functionORPad')->name('roa-dv.functionORPad');
        Route::post('/roa-dv/CreateORPad', 'DisbursementVoucherController@functionCreateORPad')->name('roa-dv.functionCreateORPad');
        Route::resource('payroll', 'PayrollController');
        Route::get('/payroll/delete/{id}', 'PayrollController@delete')->name('payroll.delete');
        Route::get('/payroll-validations', 'PayrollController@PayRollNovalidation')->name('payroll.validation');
        Route::get('/payroll-list/{year}', 'PayrollController@getPayrollList')->name('get.payrollList');
        Route::get('/invoice/autocompletePayee', 'InvoiceController@autocompletePayee')->name('invoice.autocompletePayee');
        Route::get('/invoice/autocompleteOr', 'InvoiceController@autocompleteOr')->name('invoice.autocompleteOr');
        Route::get('/invoice/autocompleteORPad', 'InvoiceController@autocompleteORPad')->name('invoice.autocompleteORPad');
        Route::get('/invoice/ORPad', 'InvoiceController@functionORPad')->name('invoice.functionORPad');
        Route::post('/invoice/CreateORPad', 'InvoiceController@functionCreateORPad')->name('invoice.functionCreateORPad');
        Route::resource('/invoice', 'InvoiceController');
        Route::group(['prefix' => 'invoices'],function(){
            Route::get('/get-invoice-list/{year}', 'InvoiceController@getInvoiceList')->name('get.invoice.list');
            Route::get('/remove-invoice/{id}', 'InvoiceController@removeInvoice')->name('remove.invoice');
        });
        Route::resource('/bank', 'BankController');
        Route::get('/get-bank-list/{year}', 'BankController@getBankList')->name('get.bank.list');
        Route::get('/remove-bank/{id}', 'BankController@removeBank')->name('remove.bank');
        Route::get('/cedula/autocompleteCedula', 'CedulaController@autocompleteCedula')->name('autocompleteCedula');
        Route::resource('/cedula', 'CedulaController');
        Route::post('/cedulas/CreateCTCPad', 'CedulaController@functionCreateCTCPad')->name('cedulas.functionCreateCTCPad');
        Route::get('/cedulas/ORPad', 'CedulaController@functionORPad')->name('cedula.functionORPad');
        Route::get('/cedulas/autocompleteCtc', 'CedulaController@autocompleteCtc')->name('cedula.autocompleteCtc');
        Route::get('/get-cedula-list/{year}', 'CedulaController@getCedulaList')->name('get.cedula.list');
        Route::get('/remove-cedula/{id}', 'CedulaController@removeCedula')->name('remove.cedula');
        Route::resource('/chart-account', 'ChartOfAccountController');
        Route::post('/account-group/store', 'ChartOfAccountController@storeAccountGroup')->name('store.accountGroup');
        Route::post('/account-ledger/store', 'ChartOfAccountController@storeAccountLedger')->name('store.accountLedger');
        Route::resource('payment','PaymentController')->except(['create']);
        Route::get('payment/create/{type}/{id}','PaymentController@create')->name('payment.create')->middleware('check.payment');
        Route::put('/account-ledger/update/{id}', 'ChartOfAccountController@updateAccountLedger')->name('update.chart-account-ledger');
        Route::put('/account-group/update/{id}', 'ChartOfAccountController@updateAccountGroup')->name('update.chart-account-group');
        Route::get('/account-group/edit/{id}', 'ChartOfAccountController@editAccountGroup')->name('edit.chart-account-group');
        Route::get('/account-ledger/edit/{id}', 'ChartOfAccountController@editAccountLedger')->name('edit.chart-account-ledger');
        Route::get('/account-ledger/delete/{id}', 'ChartOfAccountController@deleteAccountLedger')->name('delete.chart-account-ledger');
        Route::get('/account-group/delete/{id}', 'ChartOfAccountController@deleteAccountGroup')->name('delete.chart-account-group');
        Route::delete('/account-group/archive/{id}', 'ChartOfAccountController@archiveAccountGroup')->name('archive.accountGroup');
        Route::delete('/account-ledger/archive/{id}', 'ChartOfAccountController@archiveAccountLedger')->name('archive.accountLedger');
    });

    Route::get('/account/getAccount', 'AccountController@getAccount')->name('getAccount');
    Route::get('/account/image/{file}','AccountController@getImage')->name('account.image');
    Route::group(['prefix' => 'setup'], function(){
        Route::get('/account/getAccount/{year}', 'AccountController@getAccount')->name('account.getAccount');
        Route::put('/account/functionRemoveAccount/{user_id}', 'AccountController@functionRemoveAccount')->name('account.functionRemoveAccount');
        Route::get('/supplier/getSuppliers/{year}', 'SupplierController@getSuppliers')->name('supplier.getSuppliers');
        Route::get('/supplier/RemoveSuppliers/{supp_id}', 'SupplierController@RemoveSuppliers')->name('supplier.removeSuppliers');
        Route::put('/supplier/FunctionRemoveSupp/{supp_id}', 'SupplierController@FunctionRemoveSupp')->name('supplier.functionRemoveSupp');
        Route::get('/category/getCategories/{year}', 'CategoryController@getCategories')->name('category.getCategories');
        
        Route::resource('/account', 'AccountController');
        Route::group(['prefix' => 'accounts'],function(){
            Route::get('/remove-account/{id}', 'AccountController@removeAccount')->name('remove.account');
        });
        Route::resource('/inventory-status', 'InventoryStatusController');
        Route::group(['prefix' => 'inventory-statuses'],function(){
            Route::get('/remove-inventory/{id}', 'InventoryStatusController@removeInventory')->name('remove.inventory');
            Route::get('/get-inventory-status/{year}', 'InventoryStatusController@getInventoryStatus')->name('get.inventory.list');
            Route::put('/delete-inventory/{id}', 'InventoryStatusController@deleteInventory')->name('delete.inventory');
        });
        Route::resource('/supplier', 'SupplierController');
        Route::resource('/category', 'CategoryController');
        Route::get('/residents/autocompleteResidents', 'ResidentContorller@autocompleteResidents')->name('autocompleteResidents');

app/Payroll.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Payroll extends Model
{

    

    protected $table = 'payrolls';
    protected $primaryKey = 'id';
    protected $fillable = [
        'barangay', 'treasurer', 'city_municipality', 'province', 'payroll_number', 'ledger_id', 'created_at', 'updated_at', 'created_by', 'date_from', 'date_to', 'due_date',
    ];
    use SoftDeletes;
    public function getPayrollItems(){
        return $this->hasMany('App\PayrollItem','payroll_id');
    }

    public function getPayment(){
        return $this->morphOne('App\Payment','payable');
    }
    
    public function getLedger(){
        return $this->belongsTo('App\AccountLedger','ledger_id');
    }

}

resources/views/Accounting/Payroll/delete.blade.php
<form method="POST"  class="form-horizontal" action="{{ route('payroll.destroy', $id) }}" enctype="multipart/form-data">
    <input type="hidden" name="_method" value="DELETE">
    {{csrf_field()}}
    <h6> Are you sure you want to delete Payroll No. {{ $payroll->payroll_number }}?</h6>
    <div class="form-group" style="margin-top: 20px">
        <div class="col-12" align="right">
            <div class="col-12">
                <a href="{{route('invoice.index')}}" class="btn btn-secondary" data-dismiss="modal">Cancel</a>
                <button type="submit" class="btn btn-primary">Delete</button>
            </div>
        </div>
    </div>
</form>

resources/views/Accounting/Payroll/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url('/') }}">Home</a></li>
            <li class="breadcrumb-item" >Accounting</li>
            <li class="breadcrumb-item" >Transactions</li>
            <li class="breadcrumb-item" >Bills</li>
            <li class="breadcrumb-item active" aria-current="page">Payroll</li>
        </ol>
    </nav>
    <h4 class="form-head">Payroll List</h4>
    <div class="row">
        <div class="col-md-2">
            <select class="form-control" id="budget_year">
                @foreach($budget_year as $year)
                    <option value="{{ $year->year }}">{{ $year->year }}</option>
                @endforeach
                <!-- <option value="2021">2021</option> -->
            </select>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div align="right" style="margin: 0px 0px 20px 0px"><a href="{{route('payroll.create')}}"><button class="btn btn-primary"><i class="fa fa-plus" aria-hidden="true"></i> CREATE</button></a></div>
            <table class="table table-striped table-bordered table-hover text-center table-mediascreen" id="payroll_list">
                <thead class="thead-dark">
                    <tr align="center">
                    <th>Date From</th>
                    <th>Date To</th>
                    <th>Payroll No.</th>
                    <th>Action</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
@endsection
@push('scripts')
<script>
        var oTable = $("#payroll_list").DataTable(
        {
            pagingType: "full_numbers",
            processing: true,
            //serverSide: true,
            type: "GET",
            ajax:"{!! route('get.payrollList',0000) !!}",
            columns:[
                {data: "date_from","name":"date_from","width":"25%", className:"v-align text-center"},
                {data: "date_to","name":"date_to","width":"25%", className:"v-align text-center"},
                {data: "payroll_no","name":"payroll_no","width":"25%", className:"v-align text-center"},
                {data: "action","name":"action",orderable:false,searchable:false,"width":"25%"},
            ],
            select: {
                style: "multi"
            }
        }
    );
    $('#budget_year').change(function(){
        var year = $(this).val();
        var url = '{{ route("get.payrollList", ':year') }}';
        url = url.replace(':year', $(this).val());
        oTable.ajax.url(url).load();
    });
</script>
@endpush

resources/views/Accounting/Payroll/print.blade.php
@include('layouts.header')
<table class="table table-bordered margin-top">
    <tbody>
        <tr align="center">
            <td colspan="11"><b>PAYROLL</b></br></br>Period Covered: <b>{{App\Common::convertWordDateFormat($payroll->date_from)}} - {{App\Common::convertWordDateFormat($payroll->date_to)}}</b>
        
            </td>
        </tr>
        <tr>
            <td colspan="4">
                <div>
                    <p>Barangay: <u>{{ $payroll->barangay }}</u></p>
                    <p>Barangay Treasurer: <u>{{ $payroll->treasurer }}</u></p>
                </div>
            </td>   
            <td colspan="4" style="border-left-style: hidden;border-right-style:hidden">
                <div>
                    <p>City/Municipality: <u>{{ $payroll->city_municipality }}</u></p>
                    <p>Province: <u>{{ $payroll->province }}</u></p>
                </div>
            </td> 
            <td colspan="3" style="vertical-align:bottom;text-align:right">  
                <p>Payroll No: <u>{{ $payroll->payroll_number }}</u></p>
            </td>     
        </tr> 
        <tr align="center">
            <td class="v-align" rowspan="2">No.</td>
            <td class="v-align" rowspan="2">Name</td>
            <td class="v-align" rowspan="2">Position</td>
            <td class="v-align" colspan="4" class="ptpb-0rm">Compensation</td>
            <td class="v-align" colspan="2" class="ptpb-0rm">Deductions</td>
            <td class="v-align" rowspan="2">Net Amount Due</td>
            <td class="v-align" rowspan="2">Signature of Recipient</td>
        </tr>
        <tr align="center">
            <td class="v-align">Salary & Wages</td>
            <td class="v-align">Honoraria</td>
            <td class="v-align">Other Benefits</td>
            <td  class="v-align">Total</td>
            <td class="v-align">BIR w/ holding tax</td>
            <td class="v-align">Total</td>
        </tr>
        @php $total_salary = 0; $total_honoraria = 0; $total_benefits = 0; $total_com = 0; $total_bir = 0; $total_net = 0; @endphp 
        @foreach($payroll->getPayrollItems as $payrollItem)
            @php
                $total_salary += $payrollItem->salary;
                $total_honoraria += $payrollItem->honoraria;
                $total_benefits += $payrollItem->other_benefits;
                $total_com += $payrollItem->salary + $payrollItem->honoraria + $payrollItem->other_benefits;
                $total_bir += $payrollItem->bir;
                $total_net += $payrollItem->salary + $payrollItem->honoraria + $payrollItem->other_benefits - $payrollItem->bir;
            @endphp
            <tr align="center">
                <td>{{ $payrollItem->id }}</td>
                <td>{{ $payrollItem->name }}</td>
                <td>{{ $payrollItem->position }}</td>
                <td>{{ number_format($payrollItem->salary,2) }}</td>
                <td>{{ number_format($payrollItem->honoraria,2) }}</td>
                <td>{{ number_format($payrollItem->other_benefits,2) }}</td>
                <td>{{ number_format($payrollItem->salary + $payrollItem->honoraria + $payrollItem->other_benefits,2) }}</td>
                <td >{{ number_format($payrollItem->bir,2) }}</td>
                <td>{{ number_format($payrollItem->bir,2) }}</td>
                <td>{{ number_format($payrollItem->salary + $payrollItem->honoraria + $payrollItem->other_benefits - $payrollItem->bir,2) }}</td>
                <td></td>
            </tr>
        @endforeach
        <tr align="center">
            <td ></td>
            <td>TOTAL</td>
            <td></td>
            <td>₱ {{ number_format($total_salary,2) }}</td>
            <td>₱ {{ number_format($total_honoraria,2) }}</td>
            <td>₱ {{ number_format($total_benefits,2) }}</td>
            <td>₱ {{ number_format($total_com,2) }}</td>
            <td></td>
            <td>₱ {{ number_format($total_bir,2) }}</td>
            <td>₱ {{ number_format($total_net,2) }}</td>
            <td></td>
        </tr>
        <tr>
            <td colspan="2">
                <div>
                    <p><b>A. Certified</b> as to availability of appropriation for obligation in the amount of <b><u>₱{{ number_format($total_net,2) }}</u></b></p><br><br>
                    <p>Signature:______________</p>
                    <p>Printed Name: <b><u>Anna Francesca L. Maristela</u></b></p>
                    <p>Position: <u>Chairman, Com. on Appropriations</u></p>
                    <p>Date:___________________ </p>
                </div>
            </td>
            <td colspan="3">
                <div>
                    <p><b>B. Certified</b> as to availability of funds, and completeness and propriety of supporting documents.</p><br><br><br>
                    <p>Signature:______________</p>
                    <p>Printed Name: <b><u>Michelle V. Meniano</u></b></p>
                    <p>Position: <u>Barangay Treasurer</u></p>
                    <p>Date:___________________ </p>
                </div>
            </td>
            <td colspan="3">
                <div>
                    <p><b>C. Certified</b> as to validity, propriety, and legality of claim and approved for payment
                    </p><br><br><br>
                    <p>Signature:______________</p>
                    <p>Printed Name: <b><u>ESPERANZA CASTRO-LEE</u></b></p>
                    <p>Position: <u>Punong Barangay</u></p>
                    <p>Date:___________________ </p>
                </div>
            </td>
            <td colspan="3">
            <div>
                    <p><b>D. Certified</b> that each official/employee whose name appears on the above roll has been paid the amount stated opposite his name</p><br>
                    <p>Signature:______________</p>
                    <p>Printed Name: <b><u>Michelle V. Meniano</u></b></p>
                    <p>Position: <u>Barangay Treasurer</u></p>
                    <p>Date:___________________ </p>
                </div>
            </td>
        </tr>
    </tbody>
</table>    

<style>
    .margin-top{
        margin-top: 30px;
    }
    
    .v-align {
        vertical-align: middle !important;
    }
</style>

resources/views/Accounting/Payroll/show.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url('/') }}">Home</a></li>
            <li class="breadcrumb-item" >Accounting</li>
            <li class="breadcrumb-item" >Transactions</li>
            <li class="breadcrumb-item" >Bills</li>
            <li class="breadcrumb-item active" aria-current="page">Payroll</li>
        </ol>
    </nav>
    <h4 class="form-head">View Payroll</h4>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div align="right" style="margin: 0px 0px 20px 0px"><a href="{{ route('payroll.index') }}"><button class="btn btn-secondary"><i class="fa fa-chevron-left" aria-hidden="true"></i> BACK</button></a></div> 
            <div class="tab-content">
                <form method="POST"  class="form-horizontal" id="" action="" enctype="multipart/form-data">
                <div align="center"><h5>Period Covered</h5></div>
                <div align="center">
                    <h3><strong>{{App\Common::convertWordDateFormat($payroll->date_from)}} - {{App\Common::convertWordDateFormat($payroll->date_to)}}</strong></h3>
                </div>
                    <div class="form-row">      
                        <div class="form-group col-md-6">
                            <label><b>Barangay</b></label><br>
                            <p>&nbsp;{{ $payroll->barangay }}</p>
                        </div>
                        <div class="form-group col-md-6">
                            <label><b>City/Municipality</b></label><br>
                            <p>&nbsp;{{ $payroll->city_municipality }}</p>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label><b>Barangay Treasurer</b></label><br>
                            <p>&nbsp;{{ $payroll->treasurer }}</p>
                        </div>
                        <div class="form-group col-md-4">
                            <label><b>Province</b></label><br>
                            <p>&nbsp;{{ $payroll->province }}</p>
                        </div>
                        <div class="form-group col-md-2" >
                            <label><b>Payroll No.</b></label><br>
                            <p>&nbsp;{{ $payroll->payroll_number }}</p>
                        </div>
                        
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <table class="table-sm display responsive table-striped table-bordered dataTable no-footer" cellpadding="0" width="100%" cellspacing="0" align="center" role="grid" style="width: 100%;">
                                <thead class="tab_header">
                                    <tr align="center">
                                        
                                        <th style="text-align: center; width: 30.2px;"  class="pt2" tabindex="0" aria-controls="advertisement_list" rowspan="1" colspan="1" aria-sort="ascending">No.</th>
                                        <th style="text-align: center; width: 230.2px;" class="pt2" tabindex="0" aria-controls="advertisement_list" rowspan="1" colspan="1">Name</th>
                                        <th style="text-align: center; width: 20.2px;" class="pt2" tabindex="0" aria-controls="advertisement_list" rowspan="1" colspan="1">Position</th>
                                        <th style="text-align: center; width: 170.2px;" class="pt2" tabindex="0" aria-controls="advertisement_list" rowspan="1" colspan="1">Salaries & Wages</th>
                                        <th style="text-align: center; width: 130.2px;" class="pt2" tabindex="0" aria-controls="advertisement_list" rowspan="1" colspan="1">Honoraria</th>
                                        <th style="text-align: center; width: 180.2px;" class="pt2" tabindex="0" aria-controls="advertisement_list" rowspan="1" colspan="1">Other Benefits</th>
                                        <th style="text-align: center; width: 180.2px;" class="pt2" tabindex="0" aria-controls="advertisement_list" rowspan="1" colspan="1">Total</th>
                                        <th style="text-align: center; width: 180.2px;" class="pt2" tabindex="0" aria-controls="advertisement_list" rowspan="1" colspan="1">BIR w/holding Tax</th>
                                        <th style="text-align: center; width: 180.2px;" class="pt2" tabindex="0" aria-controls="advertisement_list" rowspan="1" colspan="1">Total</th>
                                        <th style="text-align: center; width: 180.2px;" class="pt2" tabindex="0" aria-controls="advertisement_list" rowspan="1" colspan="1">Net Amount Due</th>
                                        <!-- <th style="text-align: center; width: 80.2px;" class="pt2" rowspan="1" colspan="1" style="width: 83.2px;" aria-label="Action">Estimated Cost</th> -->
                                    </tr>
                                </thead>
                                <tbody id="table_purchase">
                                    @foreach($payroll->getPayrollItems as $key => $payrollItem)
                                        <tr>
                                            <td>{{ ++$key }}</td>
                                            <td>{{ $payrollItem->name }}</td>
                                            <td>{{ $payrollItem->position }}</td>
                                            <td>{{ number_format($payrollItem->salary,2) }}</td>
                                            <td>{{ number_format($payrollItem->honoraria,2) }}</td>
                                            <td>{{ number_format($payrollItem->other_benefits,2) }}</td>
                                            <td>{{ number_format($payrollItem->salary + $payrollItem->honoraria + $payrollItem->other_benefits,2) }}</td>
                                            <td>{{ number_format($payrollItem->bir,2) }}</td>
                                            <td>{{ number_format($payrollItem->bir,2) }}</td>
                                            <td>{{ number_format($payrollItem->salary + $payrollItem->honoraria + $payrollItem->other_benefits - $payrollItem->bir,2) }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                            <div align="right">
                                <label class="total-cost">Total&nbsp;<span><b>₱{{ $total_payroll }}</b></span></label>
                            </div>
                        </div>
                    </div>
                    @if(!is_null($payroll->getPayment))
                        <fieldset>
                            <legend>Payment Details</legend>
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label>Amount Received:</label>
                                    <p>₱ {{ $total_payroll }}</p>
                                </div>
                                <div class="form-group col-md-6">
                                    <label>Received Date:</label>
                                    <p>{{ App\Common::convertWordDateFormat($payroll->getPayment->date_received) }}</p>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label>Paid Into:</label>
                                    <p>{{ $payroll->getPayment->getBank->name }}</p>
                                </div>
                                <div class="form-group col-md-6">
                                    <label>Payment Method:</label>
                                    <p>{{ $payroll->getPayment->getPaymentMethod->name }}</p>
                                </div>
                            </div>
                        </fieldset>
                    @endif
                </form>
            </div>
            <div class="form-group" align="right" >
                @if(is_null($payroll->getPayment))
                    <a type="submit" href="{{ route('payment.create',['type' => 'payroll','id' => $payroll->id]) }}" class="btn btn-primary" data-form="print-invoice"><i class="fa fa-print"></i>&nbsp;PAYMENTS</a>
                @endif

                <button class="btn btn-primary print-form-css" data-form="print_payroll"><i class="fa fa-print" aria-hidden="true"></i> Print</button>
            </div>
        </div>
    </div>
    <div id="print_payroll" hidden>
        @include('Accounting.Payroll.print')
    </div>
</div>

@endsection

<style>
    .input {
        border: none;
        background-color: transparent;
    }
    .total-cost{
        font-size: 1.5rem;
        margin-right: 1rem;
    }
</style>