routes/web.php
        Route::get('/invoice/ORPad', 'InvoiceController@functionORPad')->name('invoice.functionORPad');
        Route::post('/invoice/CreateORPad', 'InvoiceController@functionCreateORPad')->name('invoice.functionCreateORPad');
        Route::resource('/invoice', 'InvoiceController');
        Route::group(['prefix' => 'invoices'],function(){
            Route::get('/get-invoice-list/{year}', 'InvoiceController@getInvoiceList')->name('get.invoice.list');
            Route::get('/remove-invoice/{id}', 'InvoiceController@removeInvoice')->name('remove.invoice');
        });
        Route::resource('/bank', 'BankController');
        Route::get('/get-bank-list/{year}', 'BankController@getBankList')->name('get.bank.list');
        Route::get('/remove-bank/{id}', 'BankController@removeBank')->name('remove.bank');
        Route::get('/cedula/autocompleteCedula', 'CedulaController@autocompleteCedula')->name('autocompleteCedula');
        Route::resource('/cedula', 'CedulaController');
        Route::post('/cedulas/CreateCTCPad', 'CedulaController@functionCreateCTCPad')->name('cedulas.functionCreateCTCPad');
        Route::get('/cedulas/ORPad', 'CedulaController@functionORPad')->name('cedula.functionORPad');
        Route::get('/cedulas/autocompleteCtc', 'CedulaController@autocompleteCtc')->name('cedula.autocompleteCtc');
        Route::get('/get-cedula-list/{year}', 'CedulaController@getCedulaList')->name('get.cedula.list');
        Route::get('/remove-cedula/{id}', 'CedulaController@removeCedula')->name('remove.cedula');
        Route::resource('/chart-account', 'ChartOfAccountController');
        Route::post('/account-group/store', 'ChartOfAccountController@storeAccountGroup')->name('store.accountGroup');
        Route::post('/account-ledger/store', 'ChartOfAccountController@storeAccountLedger')->name('store.accountLedger');
        Route::resource('payment','PaymentController')->except(['create']);
        Route::get('payment/create/{type}/{id}','PaymentController@create')->name('payment.create')->middleware('check.payment');
        Route::put('/account-ledger/update/{id}', 'ChartOfAccountController@updateAccountLedger')->name('update.chart-account-ledger');
        Route::put('/account-group/update/{id}', 'ChartOfAccountController@updateAccountGroup')->name('update.chart-account-group');
        Route::get('/account-group/edit/{id}', 'ChartOfAccountController@editAccountGroup')->name('edit.chart-account-group');
        Route::get('/account-ledger/edit/{id}', 'ChartOfAccountController@editAccountLedger')->name('edit.chart-account-ledger');
        Route::get('/account-ledger/delete/{id}', 'ChartOfAccountController@deleteAccountLedger')->name('delete.chart-account-ledger');
        Route::get('/account-group/delete/{id}', 'ChartOfAccountController@deleteAccountGroup')->name('delete.chart-account-group');
        Route::delete('/account-group/archive/{id}', 'ChartOfAccountController@archiveAccountGroup')->name('archive.accountGroup');
        Route::delete('/account-ledger/archive/{id}', 'ChartOfAccountController@archiveAccountLedger')->name('archive.accountLedger');
    });

    Route::get('/account/getAccount', 'AccountController@getAccount')->name('getAccount');
    Route::get('/account/image/{file}','AccountController@getImage')->name('account.image');
    Route::group(['prefix' => 'setup'], function(){
        Route::get('/account/getAccount/{year}', 'AccountController@getAccount')->name('account.getAccount');
        Route::put('/account/functionRemoveAccount/{user_id}', 'AccountController@functionRemoveAccount')->name('account.functionRemoveAccount');
        Route::get('/supplier/getSuppliers/{year}', 'SupplierController@getSuppliers')->name('supplier.getSuppliers');
        Route::get('/supplier/RemoveSuppliers/{supp_id}', 'SupplierController@RemoveSuppliers')->name('supplier.removeSuppliers');
        Route::put('/supplier/FunctionRemoveSupp/{supp_id}', 'SupplierController@FunctionRemoveSupp')->name('supplier.functionRemoveSupp');
        Route::get('/category/getCategories/{year}', 'CategoryController@getCategories')->name('category.getCategories');
        
        Route::resource('/account', 'AccountController');
        Route::group(['prefix' => 'accounts'],function(){
            Route::get('/remove-account/{id}', 'AccountController@removeAccount')->name('remove.account');
        });
        Route::resource('/inventory-status', 'InventoryStatusController');
        Route::group(['prefix' => 'inventory-statuses'],function(){
            Route::get('/remove-inventory/{id}', 'InventoryStatusController@removeInventory')->name('remove.inventory');
            Route::get('/get-inventory-status/{year}', 'InventoryStatusController@getInventoryStatus')->name('get.inventory.list');
            Route::put('/delete-inventory/{id}', 'InventoryStatusController@deleteInventory')->name('delete.inventory');
        });
        Route::resource('/supplier', 'SupplierController');
        Route::resource('/category', 'CategoryController');
        Route::get('/residents/autocompleteResidents', 'ResidentContorller@autocompleteResidents')->name('autocompleteResidents');
        Route::get('/residents/FunctionResidents/{res_id}', 'ResidentContorller@FunctionResidents')->name('residents.FunctionResidents');
        Route::put('/residents/FunctionRemoveResidents/{res_id}', 'ResidentContorller@FunctionRemoveResidents')->name('residents.FunctionRemoveResidents');
        Route::resource('/residents', 'ResidentContorller');
        Route::get('/residents/getResidents/{year}', 'ResidentContorller@getResidents')->name('residents.getResidents');
        Route::POST('/subcategory', 'CategoryController@storeSubCateg')->name('store.subcateg');
        Route::get('/category-delete/{id}/delete', 'CategoryController@delete')->name('category.delete');
        
        Route::get('/signatory/{id}/delete', 'SignatoryController@delete')->name('signatory.delete');
        Route::get('/signatories/getSignatories/{year}', 'SignatoryController@getSignatories')->name('signatories.list');
        Route::get('/signatory/image/{file}','SignatoryController@getImage')->name('signatory.image');
        Route::resource('/signatory', 'SignatoryController');
        Route::get('/template-signatories/{id}/delete','TemplateSignatoriesController@delete')->name('template-signatories.delete');
        Route::get('/template-signatories/getTemplates', 'TemplateSignatoriesController@getTemplates')->name('templates.list');
        Route::resource('/template-signatories', 'TemplateSignatoriesController');
    });

    Route::get('/purchase-order/list/{year}', 'PurchaseOrderController@getPurchaseOrders')->name('purchase-order.getPurchaseOrders');


    Route::group(['prefix'=>'accounting'], function(){
       
        Route::resource('/disbursement-voucher', 'DisbursementVoucherController');
        Route::get('/disbursement-vouchers/getVoucher/{year}', 'DisbursementVoucherController@getVoucher')->name('disbursement-voucher.list');
        Route::get('/disbursement-vouchers/{id}/delete', 'DisbursementVoucherController@delete')->name('disbursement-voucher.delete');
        Route::resource('/chart-account', 'ChartOfAccountController');
        Route::resource('/budget-allocation', 'BudgetAllocationController');
        Route::group(['prefix' => 'budget-allocations'],function(){
            Route::get('/get-budget-allocation', 'BudgetAllocationController@getBudgetAllocationList')->name('get.budgetallocation.list');
            Route::get('/remove-budget-allocation/{id}/delete','BudgetAllocationController@removeBudgetAllocation')->name('remove.budget-allocation');
        });
    });
 

    Route::group(['prefix' => 'procurement'], function(){
        Route::get('/canvassing/reloadtable/{id}', 'CanvassingController@reloadtable')->name('canvassing.reloadtable');
        Route::get('/canvassing-delete/{id}/delete', 'CanvassingController@delete')->name('canvassing.delete');
        Route::put('/canvassing/functionRemoveCanvassing/{id}/group/{group_id}', 'CanvassingController@functionRemoveCanvassing')->name('functionRemoveCanvassing');
        Route::get('/canvassing/getCanvassing/{year}', 'CanvassingController@getCanvassing')->name('canvassing.getCanvassing');
        Route::resource('/canvassing', 'CanvassingController');
        Route::get('/canvassing-show/{id}/show/{group_id}', 'CanvassingController@show')->name('canvassing.show');
        Route::get('/canvassing-edit/{id}/edit/{group_id}', 'CanvassingController@edit')->name('canvassing.edit');
        Route::get('/canvassing-delete/{id}/remove/{group_id}', 'CanvassingController@delete')->name('canvassing.delete');
        Route::get('/purchase-request/getPurchaseRequest/{year}', 'PurchaseRequestController@getPurchaseRequest')->name('pur.getPurchaseRequest');
        Route::get('/purchase-request/reloadtable/{pur_id}', 'PurchaseRequestController@reloadtable')->name('pur.reloadtable');
        Route::get('/purchase-request/reloadtableedit/{pur_id}', 'PurchaseRequestController@reloadtableedit')->name('pur.reloadtableedit');
        Route::get('/purchase-request/RemovePurchaseRequest/{perchase_id}', 'PurchaseRequestController@RemovePurchaseRequest')->name('pur.RemovePurchaseRequest');
        Route::get('/purchase-request/autocomplete', 'PurchaseRequestController@autocomplete')->name('pur.autocomplete');
        Route::get('/purchase-request/canvass', 'PurchaseRequestController@validationcassvas')->name('pur.canvass');
        Route::put('/purchase-request/FunctionRemovePurchaseRequest/{purchase_id}', 'PurchaseRequestController@FunctionRemovePurchaseRequest')->name('pur.FunctionRemovePurchaseRequest');
        Route::get('/purchase-request/roadetails', 'PurchaseRequestController@roadetails')->name('pur.roadetails');
        Route::get('/canvassing-delete/{id}/delete', 'CanvassingController@delete')->name('canvassing.delete');

app/Signatory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;

class Signatory extends Model
{
    //
    use SoftDeletes;

    public static function getSignatoryID(){
        $statement = DB::select("show table status like 'signatories'");
        return $statement[0]->Auto_increment;
    }
}

app/Http/Controllers/SignatoryController.php
<?php

namespace App\Http\Controllers;
use App\Signatory;
use Illuminate\Http\Request;
use App\Common;
use Yajra\DataTables\DataTables;
use Illuminate\Support\Facades\Storage;
use App\BudgetAllocation;

class SignatoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $budget_allocation = BudgetAllocation::all();
        return view('Setup.Signatory.index',[
            'budget_year' => $budget_allocation
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Setup.Signatory.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request,Signatory $sign)
    {
        //
        try{
            $filename = "";
            if($request->has('signature')){
                $imageName = 'Signatory/'.$sign->getSignatoryID().'.jpg';
                $saveImage = Common::saveImage($request->file('signature'),$imageName);
                if($saveImage){
                    $filename = $imageName;
                }
            }
            $signatory = new Signatory();
            $signatory->signatory_name = $request->input('signatory_name');
            $signatory->email = $request->input('email');
            $signatory->position = $request->input('position');
            $signatory->sign_image = $filename;

            $signatory->save();
            $response = array(
                'status' => 'success',
                'desc' => 'Signatory successfully created!'
            );
        }catch(\Exception $e){
            $response = Common::catchError($e);
        }

        return response()->json($response,200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $signatory = Signatory::findOrFail($id);
        
        return view('Setup.Signatory.show', ['signatory' => $signatory]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $signatory = Signatory::findOrFail($id);

        return view('Setup.Signatory.edit', ['signatory' => $signatory]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        try{
            $filename = "";
            $signatory = Signatory::findOrFail($id);
            $signatory->signatory_name = $request->input('signatory_name');
            $signatory->position = $request->input('position');
            $signatory->email = $request->input('email');
            if($request->has('signature')){
                $imageName = 'Signatory/'.$signatory->id.'.jpg';
                $saveImage = Common::saveImage($request->file('signature'),$imageName);
                if($saveImage){
                    $signatory->sign_image = $imageName;
                }
            }
            $signatory->save();
            $response = array(
                'status' => 'success',
                'desc' => 'Signatory successfully created!'
            );
        }catch(\Exception $e){
            $response = Common::catchError($e);
        }

        return response()->json($response,200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $signatory = Signatory::findOrFail($id)->delete();

        return redirect(route('signatory.index'));
    }

    public function delete($id){
        $signatory = Signatory::findOrFail($id);

        return view('Setup.Signatory.delete',['signatory' => $signatory]);
    }

    public function getSignatories($year){
        if($year == '0000'){
            $signatories = Signatory::all();
        }else{
            $signatories = Signatory::whereYear('created_at',$year)->get(); 
        }
        
        return DataTables::of($signatories)->addColumn('signatory_name',function($model){
            return $model->signatory_name;
        })->addColumn('position',function($model){
            return $model->position;
        })->addColumn('email',function($model){
            return $model->email;
        })->addColumn('action',function($model){
            return "<center>
                        <div class='dropdown'>
                            <button class='btn btn-primary dropdown-toggle' type='button' id='dropdownMenuButton' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
                                <i class='fa fa-bars'></i>
                            </button>
                            <div class='dropdown-menu dropdown-menu-center' aria-labelledby='dropdownMenuButton'>
                                <a class='dropdown-item' title='View Category' href='".route('signatory.show',$model->id)."'><i class='fa fa-eye' aria-hidden='true'></i> View Record</a>
                                <a class='dropdown-item' title='Edit Category' href='".route('signatory.edit',$model->id)."'><i class='fa fa-pencil' aria-hidden='true'></i> Edit Record</a>
                                <div class='dropdown-divider'></div>
                                <a class='dropdown-item popup_form' data-toggle='modal' title='Delete Signatory Record' style='cursor:pointer' data-url='".route('signatory.delete',$model->id)."'><i class='fa fa-trash' aria-hidden='true'></i> Delete Record</a>
                            </div>
                        </div>
                    </center>";
        })->make(true);
    }

    public function getImage($id){
        try{
            $signatory = Signatory::findOrFail($id);
            $file = Storage::disk('public')->get($signatory->sign_image);
            return response($file,200);
        }catch (Exception $exception){
            $response = Common::catchError($exception);
        }
    }
}

resources/views/Setup/Signatory/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url('/') }}">Home</a></li>
            <li class="breadcrumb-item">Setup</li>
            <li class="breadcrumb-item">Signatories</li>
            <li class="breadcrumb-item active" aria-current="page">New Signatory</li>
        </ol>
    </nav>
    <h4 class="form-head">Create Signatory</h4>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div align="right" style="margin: 0px 0px 20px 0px"><a href="{{route('signatory.index')}}"><button class="btn btn-secondary"><i class="fa fa-chevron-left" aria-hidden="true"></i> BACK</button></a></div>
            <div class="tab-content">
                <div class="col-12"> 
                    <div class="tab-content">
                        <form method="POST" id="signatory-form"  class="form-horizontal" action="{{ route('signatory.store') }}" enctype="multipart/form-data">
                            @csrf
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="signatory_name">Signatory Name</label>
                                    <input type="text" name="signatory_name" id="signatory_name" class="form-control" placeholder="Signatory Name">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="email">Email Address</label>
                                    <input type="text" name="email" id="email" class="form-control" placeholder="blueridge@yahoo.com">
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="position">Position</label>
                                    <input type="text" name="position" id="position" class="form-control" placeholder="Position">
                                </div>
                                <div class="form-group col-md-6">
                                    <label>Upload Signature</label><br>
                                    <input style="border: 0px;" type="file" name="signature" id="signature" class="form-control upload-signature">
                                </div>
                            </div>
                            <div class="form-group" align="right" >
                                <button type="submit" class="btn btn-primary"><span class="fa fa-floppy-o"></span> SUBMIT</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




@endsection
@push('scripts')
    <script>
        let rules1 = {
            signatory_name : {
                required: true
            },
            email: {
                required: true
            },
            position: {
                required: true
            },
            // signature: {
            //     required: true
            // }
        };
        $('#signatory-form').registerFields(rules1);
    </script>
@endpush
<style>
    .margin-top{
        margin-top:50px;
    }
</style>

resources/views/Setup/Signatory/delete.blade.php
<form method="POST" action="{{ route('signatory.destroy', $signatory->id) }}" class="form-horizontal" enctype="multipart/form-data">
{{ csrf_field() }}
<input type="hidden" name="_method" value="DELETE" >
    <h6> Are you sure you want to delete {{ $signatory->signatory_name }}?</h6>
    <br>
    <div class="form-group" style="margin-top: 20px">
        <div class="col-12" align="right">
            <div class="col-12">
                <a href="" class="btn btn-secondary" data-dismiss="modal">Cancel</a>
                <button type="submit" class="btn btn-primary">Delete</button>
            </div>
        </div>
    </div>
</form>

resources/views/Setup/Signatory/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url('/') }}">Home</a></li>
            <li class="breadcrumb-item" >Setup</li>
            <li class="breadcrumb-item">Signatories</li>
            <li class="breadcrumb-item active" aria-current="page">New Signatory</li>
        </ol>
    </nav>
    <h4 class="form-head">Edit Signatory</h4>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div align="right" style=""><a href="{{route('signatory.index')}}"><button class="btn btn-secondary"><i class="fa fa-chevron-left" aria-hidden="true"></i> BACK</button></a></div>
                <div class="tab-content">                                                
                    <form method="POST" id="signatory_edit_form"  class="form-horizontal" action="{{ route('signatory.update', $signatory->id )}}" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <div class="errors"></div>
                        <input type="hidden" name="_method" value="PUT" >
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label>Signatory Name</label>
                                <input type="text" class="form-control" name="signatory_name" value="{{ $signatory->signatory_name }}" placeholder="Signatory Name">

                            </div>
                            <div class="form-group col-md-6" id="sub_panel">
                                <label>Position</label>
                                    <input type="text" class="form-control" name="position" value="{{ $signatory->position }}" placeholder="Position">
                            </div>
                            <div class="form-group col-md-6" id="">
                                <label>Email</label>
                                    <input type="text" class="form-control" name="email" value="{{ $signatory->email }}" placeholder="Email">
                            </div>
                            <div class="form-group col-md-6" id="">
                                <label>Image</label>
                                <div class="image-container">
                                    <button id="x">
                                        <span class="fa fa-close"></span>
                                    </button>
                                    <img style="width: 100px;height: 150px;" src="{{ route('signatory.image',$signatory->id) }}" alt="">
                                </div>
                            </div>
                           
                        </div>
                        <div class="form-group" align="right" >
                            <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-saved"></span><i class="fa fa-floppy-o" aria-hidden="true"></i> UPDATE</button>
                        </div>
                    </form>                                                
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@push('scripts')
<script>
    let html = $('.image-container').html();

    $('#x').on('click',function(e){
        e.preventDefault();
        let input = '<input style="border: 0px;" type="file" name="signature" id="signature" class="form-control upload-signature">';
        $('.image-container').html(input);
    })
    let rules = {
        signatory_name : {
            required: true
        },
        email: {
            required: true
        },
        position: {
            required: true
        },
        // signature: {
        //     required: true
        // }
    };
  $('#signatory_edit_form').registerFields(rules,false);
  
</script>
@endpush

<style>
.margin-top{
        margin-top:50px;
    }
    /* Custom checkbox */
    .stored-label {
        position: relative;
        padding-left: 35px;
        margin-bottom: 12px;
        cursor: pointer;
        font-size: 16px;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }
    .stored-label input {
        position: absolute;
        opacity: 0;
        cursor: pointer;
        height: 0;
        width: 0;
    }
    .checkmark {
        position: absolute;
        top: 40px;
        left: 6rem;
        height: 25px;
        width: 25px;
        background-color: #eee;
    }
    .stored-label:hover input ~ .checkmark {
        background-color: #ccc;
    }
    .stored-label input:checked ~ .checkmark {
        background-color: #2196F3;
    }
    .checkmark:after {
        content: "";
        position: absolute;
        display: none;
    }
    .stored-label input:checked ~ .checkmark:after {
        display: block;
    }
    .stored-label .checkmark:after {
        left: 9px;
        top: 5px;
        width: 6px;
        height: 12px;
        border: solid white;
        border-width: 0 3px 3px 0;
        -webkit-transform: rotate(45deg);
        -ms-transform: rotate(45deg);
        transform: rotate(45deg);
    }
    .margin-top{
        margin-top:50px;
    }

    /* Tabs for Categories */
    .about-nav-tab .nav-tabs, .about-nav-tab .nav-tabs .nav-link {
        border: none;
        border-radius: 0;
    }
    .about-nav-tab .nav-tabs {
        margin-bottom: 40px;
    }
    .about-nav-tab .nav-tabs .nav-link.active {
        border-color: #132644 !important;
    }
    .about-nav-tab .nav-tabs .nav-link.active {
        color: white;
        background-color: #132644;
    }
    .about-nav-tab .nav-tabs .nav-link {
        color: black;
    }
    .about-nav-tab .nav-tabs .nav-items .nav-link {
        font-weight: 600;
        padding: 15px 30px;
        line-height: 1;
        border-bottom: 2px solid;
        border-color: #132644;
        font-size: 20px;
    }
    .about-nav-tab .nav-tabs .nav-link {
        border: none;
        border-radius: 0;
    }
    .about-nav-tab .nav-tabs {
        border: none;
        border-radius: 0;
    }
    .tab-content-about>.tab-pane.active {
        display: block;
    }
    .about-nav-tab .tab-content-about .tab-pane p {
        margin-bottom: 25px;
        font-size: 18px;
        color: aliceblue;
    }
    .about-nav-tab .tab-content-about .tab-pane ul {
        margin-bottom: 43px;
    }
    .tab-content-about>.tab-pane {
        display: none;
    }
    .switch {
    position: relative;
    display: inline-block;
    width: 60px;
    height: 34px;
    }
    .switch input {display:none;}
    .slider {
    position: absolute;
    cursor: pointer;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: #8593ae;
    -webkit-transition: .4s;
    transition: .4s;
    }
    .slider:before {
    position: absolute;
    content: "";
    height: 26px;
    width: 26px;
    left: 4px;
    bottom: 4px;
    background-color: white;
    -webkit-transition: .4s;
    transition: .4s;
    }
    input:checked + .slider {
    background-color: rgba(10, 122, 211, 0.82);
    }
    input:focus + .slider {
    box-shadow: 0 0 1px #2196F3;
    }
    input:checked + .slider:before {
    -webkit-transform: translateX(26px);
    -ms-transform: translateX(26px);
    transform: translateX(26px);
    }
    .slider.round {
    border-radius: 34px;
    }
    .slider.round:before {
    border-radius: 50%;
    }
    .sw-top{
    margin-top: 20px;
    }
    #x{
        border-radius: 13px;
        height: 28px;
        width: 28px;
        position: relative;
        float: right;
        background: #cc2d2d;
        color: white;
        top: -10px;
        right: 437px;
    }
</style>

resources/views/Setup/Signatory/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url('/') }}">Home</a></li>
            <li class="breadcrumb-item" >Setup</li>
            <li class="breadcrumb-item">Signatories</li>
            <li class="breadcrumb-item active" aria-current="page">New Signatory</li>
        </ol>
    </nav>
    <h4 class="form-head">Signatory List</h4>
    <div class="row">
        <div class="col-md-2">
            <select class="form-control" id="budget_year">
                @foreach($budget_year as $year)
                    <option value="{{ $year->year }}">{{ $year->year }}</option>
                @endforeach
                <!-- <option value="2021">2021</option> -->
            </select>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div align="right" style="margin: 50px 0px 10px 0px"> <a href="{{ route('signatory.create')}}"><button class="btn btn-primary"><i class="fa fa-plus" aria-hidden="true"></i>&nbsp;CREATE</button></a></div>
        </div>
        <div class="col-md-12">
            <table class="table table-striped table-bordered table-hover table-mediascreen text-center" id="signatory_list">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">Signatory Name</th>
                        <th scope="col">Position</th>
                        <th scope="col">Email Address</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                
            </table>
        </div>
    </div>
</div>

@endsection
@push('scripts')
    <script>
        var oTable =  $("#signatory_list").DataTable(
            {
                pagingType: "full_numbers",
                processing: true,
                //serverSide: true,
                type: "GET",
                ajax:"{!! route('signatories.list',0000) !!}",
                columns:[
                    {data: "signatory_name","signatory_name":"signatory_name","width":"30%"},
                    {data: "position","position":"position","width":"30%"},
                    {data: "email","email":"email","width":"25%"},
                    {data: "action","name":"action",orderable:false,searchable:false,"width":"15%"},
                ],
                select: {
                    style: "multi"
                }
            }
        );
        $('#budget_year').change(function(){
            var year = $(this).val();
            var url = '{{ route("signatories.list", ':year') }}';
            url = url.replace(':year', $(this).val());
            oTable.ajax.url(url).load();
        });
    </script>
@endpush
<style>
    .margin-top{
        margin-top:50px;
    }
</style>
 