routes/web.php
        Route::get('/invoice/ORPad', 'InvoiceController@functionORPad')->name('invoice.functionORPad');
        Route::post('/invoice/CreateORPad', 'InvoiceController@functionCreateORPad')->name('invoice.functionCreateORPad');
        Route::resource('/invoice', 'InvoiceController');
        Route::group(['prefix' => 'invoices'],function(){
            Route::get('/get-invoice-list/{year}', 'InvoiceController@getInvoiceList')->name('get.invoice.list');
            Route::get('/remove-invoice/{id}', 'InvoiceController@removeInvoice')->name('remove.invoice');
        });
        Route::resource('/bank', 'BankController');
        Route::get('/get-bank-list/{year}', 'BankController@getBankList')->name('get.bank.list');
        Route::get('/remove-bank/{id}', 'BankController@removeBank')->name('remove.bank');
        Route::get('/cedula/autocompleteCedula', 'CedulaController@autocompleteCedula')->name('autocompleteCedula');
        Route::resource('/cedula', 'CedulaController');
        Route::post('/cedulas/CreateCTCPad', 'CedulaController@functionCreateCTCPad')->name('cedulas.functionCreateCTCPad');
        Route::get('/cedulas/ORPad', 'CedulaController@functionORPad')->name('cedula.functionORPad');
        Route::get('/cedulas/autocompleteCtc', 'CedulaController@autocompleteCtc')->name('cedula.autocompleteCtc');
        Route::get('/get-cedula-list/{year}', 'CedulaController@getCedulaList')->name('get.cedula.list');
        Route::get('/remove-cedula/{id}', 'CedulaController@removeCedula')->name('remove.cedula');
        Route::resource('/chart-account', 'ChartOfAccountController');
        Route::post('/account-group/store', 'ChartOfAccountController@storeAccountGroup')->name('store.accountGroup');
        Route::post('/account-ledger/store', 'ChartOfAccountController@storeAccountLedger')->name('store.accountLedger');
        Route::resource('payment','PaymentController')->except(['create']);
        Route::get('payment/create/{type}/{id}','PaymentController@create')->name('payment.create')->middleware('check.payment');
        Route::put('/account-ledger/update/{id}', 'ChartOfAccountController@updateAccountLedger')->name('update.chart-account-ledger');
        Route::put('/account-group/update/{id}', 'ChartOfAccountController@updateAccountGroup')->name('update.chart-account-group');
        Route::get('/account-group/edit/{id}', 'ChartOfAccountController@editAccountGroup')->name('edit.chart-account-group');
        Route::get('/account-ledger/edit/{id}', 'ChartOfAccountController@editAccountLedger')->name('edit.chart-account-ledger');
        Route::get('/account-ledger/delete/{id}', 'ChartOfAccountController@deleteAccountLedger')->name('delete.chart-account-ledger');
        Route::get('/account-group/delete/{id}', 'ChartOfAccountController@deleteAccountGroup')->name('delete.chart-account-group');
        Route::delete('/account-group/archive/{id}', 'ChartOfAccountController@archiveAccountGroup')->name('archive.accountGroup');
        Route::delete('/account-ledger/archive/{id}', 'ChartOfAccountController@archiveAccountLedger')->name('archive.accountLedger');
    });

    Route::get('/account/getAccount', 'AccountController@getAccount')->name('getAccount');
    Route::get('/account/image/{file}','AccountController@getImage')->name('account.image');
    Route::group(['prefix' => 'setup'], function(){
        Route::get('/account/getAccount/{year}', 'AccountController@getAccount')->name('account.getAccount');
        Route::put('/account/functionRemoveAccount/{user_id}', 'AccountController@functionRemoveAccount')->name('account.functionRemoveAccount');
        Route::get('/supplier/getSuppliers/{year}', 'SupplierController@getSuppliers')->name('supplier.getSuppliers');
        Route::get('/supplier/RemoveSuppliers/{supp_id}', 'SupplierController@RemoveSuppliers')->name('supplier.removeSuppliers');
        Route::put('/supplier/FunctionRemoveSupp/{supp_id}', 'SupplierController@FunctionRemoveSupp')->name('supplier.functionRemoveSupp');
        Route::get('/category/getCategories/{year}', 'CategoryController@getCategories')->name('category.getCategories');
        
        Route::resource('/account', 'AccountController');
        Route::group(['prefix' => 'accounts'],function(){
            Route::get('/remove-account/{id}', 'AccountController@removeAccount')->name('remove.account');
        });
        Route::resource('/inventory-status', 'InventoryStatusController');
        Route::group(['prefix' => 'inventory-statuses'],function(){
            Route::get('/remove-inventory/{id}', 'InventoryStatusController@removeInventory')->name('remove.inventory');
            Route::get('/get-inventory-status/{year}', 'InventoryStatusController@getInventoryStatus')->name('get.inventory.list');
            Route::put('/delete-inventory/{id}', 'InventoryStatusController@deleteInventory')->name('delete.inventory');
        });
        Route::resource('/supplier', 'SupplierController');
        Route::resource('/category', 'CategoryController');
        Route::get('/residents/autocompleteResidents', 'ResidentContorller@autocompleteResidents')->name('autocompleteResidents');
        Route::get('/residents/FunctionResidents/{res_id}', 'ResidentContorller@FunctionResidents')->name('residents.FunctionResidents');
        Route::put('/residents/FunctionRemoveResidents/{res_id}', 'ResidentContorller@FunctionRemoveResidents')->name('residents.FunctionRemoveResidents');
        Route::resource('/residents', 'ResidentContorller');
        Route::get('/residents/getResidents/{year}', 'ResidentContorller@getResidents')->name('residents.getResidents');
        Route::POST('/subcategory', 'CategoryController@storeSubCateg')->name('store.subcateg');
        Route::get('/category-delete/{id}/delete', 'CategoryController@delete')->name('category.delete');
        
        Route::get('/signatory/{id}/delete', 'SignatoryController@delete')->name('signatory.delete');
        Route::get('/signatories/getSignatories/{year}', 'SignatoryController@getSignatories')->name('signatories.list');
        Route::get('/signatory/image/{file}','SignatoryController@getImage')->name('signatory.image');
        Route::resource('/signatory', 'SignatoryController');
        Route::get('/template-signatories/{id}/delete','TemplateSignatoriesController@delete')->name('template-signatories.delete');
        Route::get('/template-signatories/getTemplates', 'TemplateSignatoriesController@getTemplates')->name('templates.list');
        Route::resource('/template-signatories', 'TemplateSignatoriesController');
    });

    Route::get('/purchase-order/list/{year}', 'PurchaseOrderController@getPurchaseOrders')->name('purchase-order.getPurchaseOrders');


    Route::group(['prefix'=>'accounting'], function(){
       
        Route::resource('/disbursement-voucher', 'DisbursementVoucherController');
        Route::get('/disbursement-vouchers/getVoucher/{year}', 'DisbursementVoucherController@getVoucher')->name('disbursement-voucher.list');
        Route::get('/disbursement-vouchers/{id}/delete', 'DisbursementVoucherController@delete')->name('disbursement-voucher.delete');
        Route::resource('/chart-account', 'ChartOfAccountController');
        Route::resource('/budget-allocation', 'BudgetAllocationController');
        Route::group(['prefix' => 'budget-allocations'],function(){
            Route::get('/get-budget-allocation', 'BudgetAllocationController@getBudgetAllocationList')->name('get.budgetallocation.list');
            Route::get('/remove-budget-allocation/{id}/delete','BudgetAllocationController@removeBudgetAllocation')->name('remove.budget-allocation');
        });
    });
 

    Route::group(['prefix' => 'procurement'], function(){
        Route::get('/canvassing/reloadtable/{id}', 'CanvassingController@reloadtable')->name('canvassing.reloadtable');
        Route::get('/canvassing-delete/{id}/delete', 'CanvassingController@delete')->name('canvassing.delete');
        Route::put('/canvassing/functionRemoveCanvassing/{id}/group/{group_id}', 'CanvassingController@functionRemoveCanvassing')->name('functionRemoveCanvassing');
        Route::get('/canvassing/getCanvassing/{year}', 'CanvassingController@getCanvassing')->name('canvassing.getCanvassing');
        Route::resource('/canvassing', 'CanvassingController');
        Route::get('/canvassing-show/{id}/show/{group_id}', 'CanvassingController@show')->name('canvassing.show');
        Route::get('/canvassing-edit/{id}/edit/{group_id}', 'CanvassingController@edit')->name('canvassing.edit');
        Route::get('/canvassing-delete/{id}/remove/{group_id}', 'CanvassingController@delete')->name('canvassing.delete');
        Route::get('/purchase-request/getPurchaseRequest/{year}', 'PurchaseRequestController@getPurchaseRequest')->name('pur.getPurchaseRequest');
        Route::get('/purchase-request/reloadtable/{pur_id}', 'PurchaseRequestController@reloadtable')->name('pur.reloadtable');
        Route::get('/purchase-request/reloadtableedit/{pur_id}', 'PurchaseRequestController@reloadtableedit')->name('pur.reloadtableedit');
        Route::get('/purchase-request/RemovePurchaseRequest/{perchase_id}', 'PurchaseRequestController@RemovePurchaseRequest')->name('pur.RemovePurchaseRequest');
        Route::get('/purchase-request/autocomplete', 'PurchaseRequestController@autocomplete')->name('pur.autocomplete');
        Route::get('/purchase-request/canvass', 'PurchaseRequestController@validationcassvas')->name('pur.canvass');
        Route::put('/purchase-request/FunctionRemovePurchaseRequest/{purchase_id}', 'PurchaseRequestController@FunctionRemovePurchaseRequest')->name('pur.FunctionRemovePurchaseRequest');
        Route::get('/purchase-request/roadetails', 'PurchaseRequestController@roadetails')->name('pur.roadetails');
        Route::get('/canvassing-delete/{id}/delete', 'CanvassingController@delete')->name('canvassing.delete');

resources/views/Setup/Residents/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url('/') }}">Home</a></li>
            <li class="breadcrumb-item" >Setup</li>
            <li class="breadcrumb-item active" aria-current="page">Residents</li>
        </ol>
    </nav>
    <h4 class="form-head">Create Residents</h4>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div align="right" style="margin: 0px 0px 20px 0px"><a href="{{route('residents.index')}}"><button class="btn btn-secondary"><i class="fa fa-chevron-left" aria-hidden="true"></i> BACK</button></a></div> 
            <div class="tab-content">
                <form method="POST" id="residents_form" class="form-horizontal" action="{{route('residents.store')}}" enctype="multipart/form-data">
                    <div class="errors"></div>
                    {{csrf_field()}}
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Full Name</label>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <input type="text" class="form-control" name="first_name" id="first_name"  placeholder="First Name" autocomplete="off">
                        </div>
                        <div class="form-group col-md-4">
                            <input type="text" class="form-control" name="last_name" id="last_name"  placeholder="Last Name" autocomplete="off">
                        </div>
                        <div class="form-group col-md-3">
                            <input type="text" class="form-control" name="middle_initial" id="middle_initial"  placeholder="Middle Name" autocomplete="off">
                            <input type="text" class="form-control" name="name" id="name"  placeholder="Middle Person" autocomplete="off" hidden>
                        </div>
                        <div class="form-group col-md-1">
                            <input type="text" class="form-control" name="quantifier" id="quantifier"  placeholder="Quantifier" autocomplete="off">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Address</label>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>No.</label>
                            <input type="text" class="form-control" onkeypress="return isNumberKeySlash(event);" name="address_no" id="address_no"  placeholder="No" autocomplete="off">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Street</label>
                            <input type="text" class="form-control" name="street" id="street"  placeholder="Street" autocomplete="off">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Highest Education Attainment</label>
                            <input type="text" class="form-control" id="highest_education" name="highest_education" placeholder="Highest Education Attainment" autocomplete="off">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Role Type</label>
                            <select class="form-control" name="role_type" id="role_type">
                                <option value="">Select Role Type</option>
                                @foreach($role as $val)
                                    <option value="{{ $val->id }}">{{ $val->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Cluster No.</label>
                            <input type="text" class="form-control" onkeypress="return isNumberKeySlash(event);"  name="cluster_no" id="cluster_no"  placeholder="Cluster No" autocomplete="off">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Household No.</label>
                            <input type="text" class="form-control" onkeypress="return isNumberKeySlash(event);"  name="household_no" id="household_no"  placeholder="Household No" autocomplete="off">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Date of Birth</label>
                            <input type="" class="form-control datetimepicker" name="birth_date" id="birth_date"  placeholder="Date of Birth" autocomplete="off">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Place of Birth</label>
                            <input type="text" class="form-control" id="birth_place" name="birth_place" placeholder="Place of Birth" autocomplete="off">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Citizenship</label>
                            <input type="text" class="form-control" id="citizenship" name="citizenship" placeholder="Citizenship" autocomplete="off">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Sex</label>
                            <select class="form-control" name="sex" id="sex">
                                <option value="">Select Gender</option>
                                <option value="0">Female</option>
                                <option value="1">Male</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Civil Status</label>
                            <select class="form-control" name="civil_status" id="civil_status">
                                <option value="">Select Civil Status</option>
                                <option value="1">Single</option>
                                <option value="2">Married</option>
                                <option value="3">Widowed</option>
                                <option value="4">Divorced</option>
                            </select>
                        </div>
                        <div class="form-group col-md-6">
                            <label>Religion.</label>
                            <input type="text" class="form-control" id="religion" name="religion" placeholder="Religion" autocomplete="off">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Health Status</label>
                            <input type="text" class="form-control" id="health_status" name="health_status" placeholder="Health Status" autocomplete="off">
                        </div>
                        <div class="form-group col-md-6">
                            <label>Contact No.</label>
                            <input type="number" class="form-control price" id="contact_number" name="contact_number" placeholder="Contact No." autocomplete="off">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Occupation</label>
                            <input type="text" class="form-control" id="occupation" name="occupation" placeholder="Occupation" autocomplete="off">
                        </div>
                    </div>
                    <div class="form-group" align="right" >
                        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-floppy-saved"></span><i class="fa fa-floppy-o" aria-hidden="true"></i> SUBMIT</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@push('scripts')
    <script>
        // $(".price").number(true,2);
        let rules = {
            first_name : {
                required: true,
            },
            last_name : {
                required: true,
            },
            middle_name : {
                required: true,
            },
            street : {
                required: true,
            },
            address_no : {
                required: true,
            },
            cluster_no : {
                required: true,
            },
            household_no : {
                required: true,
            },
            birth_date : {
                required: true,
            },
            birth_place : {
                required: true,
            },
            civil_status : {
                required: true,
            },
            religion : {
                required: true,
            },
            health_status : {
                required: true,
            },
            contact_no : {
                required: true,
            },
            highest_education : {
                required: true,
            }, 
            citizenship : {
                required: true,
            },
            role_type : {
                required: true,
            },
            sex : {
                required: true,
            },
        };
        $('#residents_form').registerFields(rules);

        // allow letters and whitespaces only.
        $(".text-only").keydown(function(event){
            var inputValue = event.which;
            if(!(inputValue >= 65 && inputValue <= 120) && (inputValue != 32 && inputValue != 0)) { 
                event.preventDefault(); 
            }
        });
        function isNumberKeySlash(evt) {
            var charCode = (evt.which) ? evt.which : event.keyCode;
                if (charCode != 47 && charCode > 32
                && (charCode < 48 || charCode > 57))
                return false;
            return true;
        }
        // $( "#first_name" ).autocomplete({
        //     source: function(request, response) {
        //             $.ajax({
        //             url: "{{route('autocompleteResidents')}}",
        //             data: {
        //                     term : request.term
        //             },
                    
        //             dataType: "json",
        //             success: function(data){
                      
        //             var resp = $.map(data,function(obj){
        //                 return obj.name;
        //             }); 
        //             response(resp);
        //             auto_data = data;
                    
        //             }
        //         });
                
        //     },
        //     select: function(event,ui){
        //         event.preventDefault();
        //         event.stopImmediatePropagation()
        //         $.map(auto_data,function(obj){
        //             if(ui.item.label == obj.name){
        //                 var name = obj.name;
        //                 var data = name.split(" ");
        //                 var address = obj.address;
        //                 var values = address.split(" ");
        //                 $('#first_name').val(data[0]);
        //                 $('#last_name').val(data[2]);
        //                 $('#address_no').val(values[0]);
        //                 $('#street').val(values[1]);
        //                 $('#middle_name').val(data[1]);
        //                 $('#birth_date').val(obj.birth_date);
        //                 $('#birth_place').val(obj.birth_place);
        //                 $('#contact_no').val(obj.contact_number);
        //                 $('#sex').val(obj.sex);
        //                 $('#citizenship').val(obj.citizenship);
        //                 $('#civil_status').val(obj.civil_status);
        //                 $('#tin').val(obj.tin);
        //             }
        //         }); 
        //     },
        // });
        // $('.ui-autocomplete-clear').click(function(){
        //         $('#first_name').val('');
        //         $('#last_name').val('');
        //         $('#address').val('');
        //         $('#middle_name').val('');
        //         $('#birth_date').val('');
        //         $('#birth_place').val('');
        //         $('#sex').val('');
        //         $('#address_no').val();
        //         $('#street').val();
        //         $('#civil_status').val('');
        //         $('#citizenship').val('');
        //         $('#contact_no').val(''); 
        //         $('#tin').val(''); 
        // });
        $('#contact_person').keydown(function (e) {
            if (e.altKey) {
                e.preventDefault();
            } else {
                var key = e.keyCode;
                if (!((key == 8) || (key == 32) || (key == 46) || (key >= 35 && key <= 40) || (key >= 65 && key <= 90))) {
                e.preventDefault();
                }
            }
            });
    </script>
@endpush

@endsection
<style>
    .margin-top{
        margin-top:50px;
    }
</style>

resources/views/Setup/Residents/delete.blade.php
<form method="POST" id="remove_res_form"  class="form-horizontal" action="{{ route('residents.FunctionRemoveResidents',$GeneralUser->id)}}" enctype="multipart/form-data">
    <input type="hidden" name="_method" value="PUT">
    {{csrf_field()}}
    <h6> Are you sure you want to delete {{ $name[0] }} {{ !empty($name[1]) ? $name[1] : '' }} {{ !empty($name[2]) ? $name[2] : '' }}?</h6>
    <div class="form-group" style="margin-top: 20px">
        <div class="col-12" align="right">
            <div class="col-12">
                <a href="{{route('residents.index')}}" class="btn btn-secondary" data-dismiss="modal">Cancel</a>
                <button type="submit" class="btn btn-primary">Delete</button>
            </div>
        </div>
    </div>
</form>

resources/views/Setup/Residents/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url('/') }}">Home</a></li>
            <li class="breadcrumb-item" >Setup</li>
            <li class="breadcrumb-item active" aria-current="page">Suppliers</li>
        </ol>
    </nav>
    <h4 class="form-head">Residents List</h4>
    <div class="row">
        <div class="col-md-2">
            <select class="form-control" id="budget_year">
                @foreach($budget_year as $year)
                    <option value="{{ $year->year }}">{{ $year->year }}</option>
                @endforeach
                <!-- <option value="2021">2021</option> -->
            </select>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div align="right" style="margin: 0px 0px 20px 0px"> <a href="{{ route('residents.create')}}"><button class="btn btn-primary"><i class="fa fa-plus" aria-hidden="true"></i> CREATE</button></a></div>
            <table class="table table-striped table-bordered table-hover table-mediascreen" id="supplier_residents">
                <thead class="thead-dark">
                    <tr align="center">
                        <th scope="col">ID</th>
                        <th scope="col">Residents Name</th>
                        <th scope="col">Contact No.</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody >
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection
<style>
</style>
@push('scripts')
<script>
         var oTable = $("#supplier_residents").DataTable(
            {
                pagingType: "full_numbers",
                processing: true,
                //serverSide: true,
                type: "GET",
                ajax:"{!! route('residents.getResidents',0000) !!}",
                columns:[
                    {data: "id","name":"id","width":"30%", className:"v-align text-center"},
                    {data: "name","name":"name","width":"30%", className:"v-align text-center"},
                    {data: "contact_number","name":"contact_number","width":"20%", className:"v-align text-center"},
                    {data: "action","name":"action",orderable:false,searchable:false,"width":"20%"},
                ],
                select: {
                    style: "multi"
                }
            }
        );
        $('#budget_year').change(function(){
            var year = $(this).val();
            var url = '{{ route("residents.getResidents", ':year') }}';
            url = url.replace(':year', $(this).val());
            oTable.ajax.url(url).load();
        });
    </script>
@endpush