routes/web.php
        Route::get('/consumables/getConsumables/{year}', 'ConsumablesController@getConsumables')->name('consumables.getConsumables');
        Route::resource('/assign-equipment','AssignEquipmentController');
        Route::get('/remove-equipment/{id}', 'OfficeEquipmentController@removeEquipment')->name('removeEquipment');
        Route::put('/equipment/functionRemoveEquipment/{id}', 'OfficeEquipmentController@functionRemoveEquipment')->name('equipment.functionRemoveEquipment');
        Route::resource('/assign-equipment','AssignEquipmentController');
        Route::get('/office-equipment/getEquipments/{year}', 'OfficeEquipmentController@getEquipments')->name('equipment.getEquipments');
        Route::resource('/office-equipment', 'OfficeEquipmentController');
        Route::resource('/receiving', 'ReceivingController');
        Route::get('/consumables/image/{file}','ConsumablesController@getImage')->name('consumables.image');
        Route::get('/consumables/archived/{id}','ConsumablesController@archived')->name('consumable.archived');
        Route::get('/get-receiving/supplier', 'ReceivingController@supplierName')->name('get.supplier.name');
        Route::group(['prefix' => 'receivings'],function(){
            Route::get('/remove-receiving/{id}', 'ReceivingController@removeReceiving')->name('remove.receiving');
            Route::get('/get-receiving/{id}', 'ReceivingController@getPurchaseReceiving')->name('get.receiving');
            Route::get('/get-receivings/getReloadtable', 'ReceivingController@getReloadtable')->name('getReloadtable');
            Route::get('/get-receiving-list/{year}', 'ReceivingController@getReceivingList')->name('get.receiving.list');
            Route::put('/get-receiving/functionRemoveInventoryReceiving/{id}', 'ReceivingController@functionRemoveInventoryReceiving')->name('functionRemoveInventoryReceiving');

        });
        Route::get('/new-inventory/reloadtable/{id}', 'NewInventoryController@reloadtable')->name('new-inventory.reloadtable');
        Route::resource('/new-inventory', 'NewInventoryController');
    });
    Route::get('/disbursement-voucher/autocompleteClaimant', 'DisbursementVoucherController@autocompleteClaimant')->name('dv.autocompleteClaimant');
    Route::group(['prefix'=>'accounting'], function(){
        Route::resource('/roa-dv', 'DisbursementVoucherController');
        Route::get('/roa-dv/{id}/delete', 'DisbursementVoucherController@delete')->name('roa-dv.delete');
        Route::get('/roa-dv/{id}/print', 'DisbursementVoucherController@print')->name('roa-dv.print');
        Route::get('/roa-dvs/autocompleteOr', 'DisbursementVoucherController@autocompleteOr')->name('roa-dv.autocompleteOr');
        Route::get('/roa-dvs/ORPad', 'DisbursementVoucherController@functionORPad')->name('roa-dv.functionORPad');
        Route::post('/roa-dv/CreateORPad', 'DisbursementVoucherController@functionCreateORPad')->name('roa-dv.functionCreateORPad');
        Route::resource('payroll', 'PayrollController');
        Route::get('/payroll/delete/{id}', 'PayrollController@delete')->name('payroll.delete');
        Route::get('/payroll-validations', 'PayrollController@PayRollNovalidation')->name('payroll.validation');
        Route::get('/payroll-list/{year}', 'PayrollController@getPayrollList')->name('get.payrollList');
        Route::get('/invoice/autocompletePayee', 'InvoiceController@autocompletePayee')->name('invoice.autocompletePayee');
        Route::get('/invoice/autocompleteOr', 'InvoiceController@autocompleteOr')->name('invoice.autocompleteOr');
        Route::get('/invoice/autocompleteORPad', 'InvoiceController@autocompleteORPad')->name('invoice.autocompleteORPad');
        Route::get('/invoice/ORPad', 'InvoiceController@functionORPad')->name('invoice.functionORPad');
        Route::post('/invoice/CreateORPad', 'InvoiceController@functionCreateORPad')->name('invoice.functionCreateORPad');
        Route::resource('/invoice', 'InvoiceController');
        Route::group(['prefix' => 'invoices'],function(){
            Route::get('/get-invoice-list/{year}', 'InvoiceController@getInvoiceList')->name('get.invoice.list');
            Route::get('/remove-invoice/{id}', 'InvoiceController@removeInvoice')->name('remove.invoice');
        });
        Route::resource('/bank', 'BankController');
        Route::get('/get-bank-list/{year}', 'BankController@getBankList')->name('get.bank.list');
        Route::get('/remove-bank/{id}', 'BankController@removeBank')->name('remove.bank');
        Route::get('/cedula/autocompleteCedula', 'CedulaController@autocompleteCedula')->name('autocompleteCedula');
        Route::resource('/cedula', 'CedulaController');
        Route::post('/cedulas/CreateCTCPad', 'CedulaController@functionCreateCTCPad')->name('cedulas.functionCreateCTCPad');
        Route::get('/cedulas/ORPad', 'CedulaController@functionORPad')->name('cedula.functionORPad');
        Route::get('/cedulas/autocompleteCtc', 'CedulaController@autocompleteCtc')->name('cedula.autocompleteCtc');
        Route::get('/get-cedula-list/{year}', 'CedulaController@getCedulaList')->name('get.cedula.list');
        Route::get('/remove-cedula/{id}', 'CedulaController@removeCedula')->name('remove.cedula');
        Route::resource('/chart-account', 'ChartOfAccountController');
        Route::post('/account-group/store', 'ChartOfAccountController@storeAccountGroup')->name('store.accountGroup');
        Route::post('/account-ledger/store', 'ChartOfAccountController@storeAccountLedger')->name('store.accountLedger');
        Route::resource('payment','PaymentController')->except(['create']);
        Route::get('payment/create/{type}/{id}','PaymentController@create')->name('payment.create')->middleware('check.payment');
        Route::put('/account-ledger/update/{id}', 'ChartOfAccountController@updateAccountLedger')->name('update.chart-account-ledger');
        Route::put('/account-group/update/{id}', 'ChartOfAccountController@updateAccountGroup')->name('update.chart-account-group');
        Route::get('/account-group/edit/{id}', 'ChartOfAccountController@editAccountGroup')->name('edit.chart-account-group');
        Route::get('/account-ledger/edit/{id}', 'ChartOfAccountController@editAccountLedger')->name('edit.chart-account-ledger');
        Route::get('/account-ledger/delete/{id}', 'ChartOfAccountController@deleteAccountLedger')->name('delete.chart-account-ledger');
        Route::get('/account-group/delete/{id}', 'ChartOfAccountController@deleteAccountGroup')->name('delete.chart-account-group');
        Route::delete('/account-group/archive/{id}', 'ChartOfAccountController@archiveAccountGroup')->name('archive.accountGroup');
        Route::delete('/account-ledger/archive/{id}', 'ChartOfAccountController@archiveAccountLedger')->name('archive.accountLedger');
    });

    Route::get('/account/getAccount', 'AccountController@getAccount')->name('getAccount');
    Route::get('/account/image/{file}','AccountController@getImage')->name('account.image');
    Route::group(['prefix' => 'setup'], function(){
        Route::get('/account/getAccount/{year}', 'AccountController@getAccount')->name('account.getAccount');
        Route::put('/account/functionRemoveAccount/{user_id}', 'AccountController@functionRemoveAccount')->name('account.functionRemoveAccount');
        Route::get('/supplier/getSuppliers/{year}', 'SupplierController@getSuppliers')->name('supplier.getSuppliers');
        Route::get('/supplier/RemoveSuppliers/{supp_id}', 'SupplierController@RemoveSuppliers')->name('supplier.removeSuppliers');
        Route::put('/supplier/FunctionRemoveSupp/{supp_id}', 'SupplierController@FunctionRemoveSupp')->name('supplier.functionRemoveSupp');
        Route::get('/category/getCategories/{year}', 'CategoryController@getCategories')->name('category.getCategories');
        
        Route::resource('/account', 'AccountController');
        Route::group(['prefix' => 'accounts'],function(){
            Route::get('/remove-account/{id}', 'AccountController@removeAccount')->name('remove.account');
        });
        Route::resource('/inventory-status', 'InventoryStatusController');
        Route::group(['prefix' => 'inventory-statuses'],function(){
            Route::get('/remove-inventory/{id}', 'InventoryStatusController@removeInventory')->name('remove.inventory');
            Route::get('/get-inventory-status/{year}', 'InventoryStatusController@getInventoryStatus')->name('get.inventory.list');
            Route::put('/delete-inventory/{id}', 'InventoryStatusController@deleteInventory')->name('delete.inventory');
        });
        Route::resource('/supplier', 'SupplierController');
        Route::resource('/category', 'CategoryController');
        Route::get('/residents/autocompleteResidents', 'ResidentContorller@autocompleteResidents')->name('autocompleteResidents');
        Route::get('/residents/FunctionResidents/{res_id}', 'ResidentContorller@FunctionResidents')->name('residents.FunctionResidents');
        Route::put('/residents/FunctionRemoveResidents/{res_id}', 'ResidentContorller@FunctionRemoveResidents')->name('residents.FunctionRemoveResidents');
        Route::resource('/residents', 'ResidentContorller');
        Route::get('/residents/getResidents/{year}', 'ResidentContorller@getResidents')->name('residents.getResidents');
        Route::POST('/subcategory', 'CategoryController@storeSubCateg')->name('store.subcateg');
        Route::get('/category-delete/{id}/delete', 'CategoryController@delete')->name('category.delete');
        
        Route::get('/signatory/{id}/delete', 'SignatoryController@delete')->name('signatory.delete');
        Route::get('/signatories/getSignatories/{year}', 'SignatoryController@getSignatories')->name('signatories.list');
        Route::get('/signatory/image/{file}','SignatoryController@getImage')->name('signatory.image');
        Route::resource('/signatory', 'SignatoryController');

app/Cedula.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Cedula extends Model
{
    protected $primaryKey = 'id';
    protected $table = 'cedulas';
    protected $fillable = [
        'ledger_id', 'issued_date','interest','ctc','cedula_id','created_by','item_1','item_2','item_3','item_4','item_5','item_6','item_7','item_8','item_9','item_10','created_at','updated_at','due_date'];
    public $timestamps = false;

    public function getPayment(){
        return $this->morphOne('App\Payment','payable');
    }

    public function getLedger(){
        return $this->belongsTo('App\AccountLedger','ledger_id');
    }
    
    public function userData(){
        return $this->belongsTo('App\GeneralUser','cedula_id');
    }
}

app/Invoice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Invoice extends Model
{
    protected $primaryKey = 'id';
    protected $table = 'invoices';
    protected $fillable = ['payee_id','ledger_id', 'collection_nature', 'or_number', 'invoice_date', 'created_at', 'updated_at', 'deleted_at','due_date'];
    public $timestamps = false;

    use SoftDeletes;

    public function getPayee(){
        return $this->belongsTo('App\GeneralUser','payee_id');
    }

    public function getLedger(){
        return $this->belongsTo('App\AccountLedger','ledger_id');
    }

    public function getInvoice(){
        return $this->hasOne('App\InvoiceItem','id');
    }

    public function getPayment(){
        return $this->morphOne('App\Payment','payable');
    }
}

resources/views/Accounting/Invoice/Cedula/cd_pad.blade.php
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="tab-content">
                
                    <form method="POST" class="form-horizontal" id="invoice_ctcpad_form" action="{{route('cedulas.functionCreateCTCPad')}}" enctype="multipart/form-data">
                    @if($or_settings == null)
                        <div class="errors"></div>
                        {{csrf_field()}}
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label>CTC Pad Start</label>
                                <input type="text" class="form-control pad_start" id="pad_start" name="pad_start" placeholder="CTC Pad Start" autocomplete="off">
                            </div>
                            <div class="form-group col-md-6">
                                <label>CTC Pad Quantity</label>
                                <input type="text" class="form-control" id="pad_end" name="pad_end" placeholder="CTC Pad Quantity" autocomplete="off">
                            </div>
                        </div>
                        <div class="form-group" align="right" >
                            <button type="submit" class="btn btn-primary"><i class="fa fa-floppy-o" aria-hidden="true"></i> SUBMIT</button>
                        </div>
                    @else
                        <table class="table  table-responsive" style="width: 100%">
                            <tr>
                                <td>Total CTC Count</td>
                                <td>{{ $or_pads->sum('cd_pad_quantity') }}</td>
                            </tr>
                            <tr>
                                <td>Beginning Balance</td>
                                <td>{{ $or_pads->first()['cd_pad_start'] }}</td>
                            </tr>
                            <tr>
                                <td>Issued Cedula </td>
                                <td>{{ $Cedula->count() }}</td>
                            </tr>
                            <tr>
                                <td>End Balance</td>
                                <td>{{ $or_pads->first()['cd_pad_start'] + $or_pads->sum('cd_pad_quantity') - 1 }}</td>
                            </tr>
                        </table>
                        <div id="append_form"></div>
                        <a href="#" id="add_replenishment"><p><span class="fa fa-plus"></span> Add Replenishment</p></a>
                        <a href="#"><p><span class="fa fa-undo"></span> Reset OR Settings</p></a>
                    @endif
                    </form>
                
            </div>
        </div>
    </div>
    <script>
        $('#add_replenishment').on('click',function () {
            let append_html =
            '{{csrf_field()}}' + 
            ' <div class="form-row">\n' +
            '   <div class="form-group col-md-6">\n' +
            '       <label>CTC Pad Start</label>\n' +
            '       <input type="text" class="form-control newInput pad_start" id="pad_start" name="pad_start" placeholder="CTC Pad Start" autocomplete="off">\n' +
            '   </div>\n' +
            '   <div class="form-group col-md-6">\n' +
            '       <label>CTC Pad Quantity</label>\n' +
            '       <input type="text" class="form-control newInput" id="pad_end" name="pad_end" placeholder="CTC Pad Quantity" autocomplete="off">\n' +
            '   </div>\n' +
            '</div>' +
            '<div class="form-group" align="right" >\n' +
            '   <button type="submit" class="btn btn-primary"><i class="fa fa-floppy-o" aria-hidden="true"></i> SUBMIT</button>\n' +
            '</div>'
            $('#append_form').html(append_html);
            $('.newInput').each( function () {
                $(this).rules('add',{
                    'required' : true
                })
            });
            $('.pad_start').change(function(){
                if($(this).val() != null){
                    $.ajax({
                        url: "{{route('invoice.autocompleteORPad')}}",
                        data: {
                            OR : $(this).val()
                        },
                        dataType: "json",
                        success: function(data){
                            if(data>0){
                                toastMessage('Warning!',"This OR Pad Number already Existed!","warning");
                            }
                            
                        }
                    });
                }
            })
        })
    $('.pad_start').change(function(){
        if($(this).val() != null){
             $.ajax({
                url: "{{route('invoice.autocompleteORPad')}}",
                data: {
                    OR : $(this).val()
                },
                dataType: "json",
                success: function(data){
                    if(data == "duplicat"){
                        toastMessage('Warning!',"This OR Pad Number already Existed!","warning");
                    }
                    // if(data == "maxorpad"){
                    //     toastMessage('Warning!',"Sorry But","warning");
                    // }
                    
                }
            });
        }
    })
     $(document).ready(function(){
        let pad_rules = {
            pad_start : {
                required: true
            },
            pad_end : {
                required: true
            }
        }; 
        $('#invoice_ctcpad_form').registerFields(pad_rules);
     });
    </script>

resources/views/Accounting/Invoice/Cedula/delete.blade.php
<form method="POST"  class="form-horizontal" action="{{ route('cedula.destroy', $id) }}" enctype="multipart/form-data">
    <input type="hidden" name="_method" value="DELETE">
    {{csrf_field()}}
    <h6> Are you sure you want to delete  {{ $Cedula->userData->first_name }} {{ $Cedula->userData->last_name }}?</h6>
    <div class="form-group" style="margin-top: 20px">
        <div class="col-12" align="right">
            <div class="col-12">
                <a href="{{route('cedula.index')}}" class="btn btn-secondary" data-dismiss="modal">Cancel</a>
                <button type="submit" class="btn btn-primary">Delete</button>
            </div>
        </div>
    </div>
</form>

resources/views/Accounting/Invoice/Cedula/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url('/') }}">Home</a></li>
        <li class="breadcrumb-item" >Accounting</li>
        <li class="breadcrumb-item">Transactions</li>
        <li class="breadcrumb-item">Invoice</li>
        <li class="breadcrumb-item active" aria-current="page">Cedula</li>
    </ol>
    </nav>
    <h4 class="form-head">Cedula List</h4>
    <div class="row">
        <div class="col-md-2">
            <select class="form-control" id="budget_year">
                @foreach($budget_year as $year)
                    <option value="{{ $year->year }}">{{ $year->year }}</option>
                @endforeach
                <!-- <option value="2021">2021</option> -->
            </select>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div align="right" style="margin: 0px 0px 20px 0px"><a href="{{route('cedula.create')}}"><button class="btn btn-primary"><i class="fa fa-plus" aria-hidden="true"></i> CREATE</button></a></div>
                <table class="table table-striped table-bordered table-hover text-center table-mediascreen" id="cedula_list">
                    <thead class="thead-dark">
                        <tr align="center">
                            <th width="20%">First Name</th>
                            <th width="20%">Last Name</th> 
                            <th width="20%">CTC No.</th>
                            <th width="20%">Tin</th>
                            <th width="20%">Action</th>
                        </tr>
                    </thead>
                </table>
        </div>
    </div>
</div>
@endsection
<style>
    .margin-top{
        margin-top:50px;
    }
</style>
@push('scripts')
    <script>
        var oTable = $("#cedula_list").DataTable({
            pagingType: "full_numbers",
                processing: true,
                //serverSide: true,
                type: "GET",
                ajax:"{!! route('get.cedula.list',0000) !!}",
                columns:[
                    {data: "first_name","name":"first_name","width":"20%", className:"v-align text-center"},
                    {data: "last_name","name":"last_name","width":"20%", className:"v-align text-center"},
                    {data: "ctc","name":"ctc","width":"20%", className:"v-align text-center"},
                    {data: "tin","name":"tin","width":"20%", className:"v-align text-center"},
                    {data: "action","name":"action",orderable:false,searchable:false,"width":"20%"},
                ],
                select: {
                    style: "multi"
                }
        });
        $('#budget_year').change(function(){
            var year = $(this).val();
            var url = '{{ route("get.cedula.list", ':year') }}';
            url = url.replace(':year', $(this).val());
            oTable.ajax.url(url).load();
        });
    </script>
@endpush